### PR TITLE
Refactor the appointment form with Shadcn

### LINKED ISSUE #42: As a user, I should only be able to select appointments on dates that are available
This issue pertains to users being able to only select valid dates for appointment requests

AC:

- [ ] Users should not be able to book appointments before the present date
- [ ] The next select-able date for an appointment should be >24 hours from now()
- [ ] The days that the office are closed should be disabled/unavailable

Optional AC (requires research)

- [ ] Known public holidays should be disabled/unavailable. Check for Google Calendar API or similar

### PR DESCRIPTION
**Pull request by mentalcaries**
## Description

For this PR I:
- refactored the appointment form to use Shadcn ui components
- added Zod to validate the form schema
- refactored the appointment details to a separate component (using shadcn's Card component)
- replaced the confirmation popup with a toast (that also handles bad requests).
- updated the Is this an emergency to use a checkbox (for a boolean response)

Also of note, I updated the backend to correct the requested appointment date to a Date type (thanks @5hraddha for spotting that).
Global types have also been adjusted

Automatically updating available dates will be handled in a different PR

## Related Issue
Closes #42 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before
image

image

image

### After
image

image

image

## Testing Steps / QA Criteria

Be sure to run `npm i` to get all the components installed

### CODE REVIEW

**Review by 5hraddha — CHANGES_REQUESTED** [review]
@mentalcaries Good job on refactoring and plugging the the Shadcn library 🚀 ! There are few things to be looked upon:
1. For accessibility purposes, when a user is focused on a form, the Enter key should submit the form. That is somehow not happening for me when I test the code. Could you please check on that.
2. All the required fields of the form should have a visual indicator. Having that will be great..
3. The **Submit** button for the form should be disabled when the user has not provided any values yet for the required fields.
4. The name of the **Submit** button itself will be more self explanatory if we keep it as **Request Appointment** or **Submit Request** or something like that.

**Comment by 5hraddha** [comment]
> @mentalcaries Good job on refactoring and plugging the the Shadcn library 🚀 ! There are few things to be looked upon:
> 
> 1. For accessibility purposes, when a user is focused on a form, the Enter key should submit the form. That is somehow not happening for me when I test the code. Could you please check on that.
> 2. All the required fields of the form should have a visual indicator. Having that will be great..
> 3. The **Submit** button for the form should be disabled when the user has not provided any values yet for the required fields.
> 4. The name of the **Submit** button itself will be more self explanatory if we keep it as **Request Appointment** or **Submit Request** or something like that.

Am sorry for the point # 1, I didn't realise that it works like that only when the focus is on the text inputs until you pointed out in our discussion offline. Thanks for that!

**Comment by mentalcaries** [comment]
Updates to this PR
- Appointment preview Dialog from @Amanda2900 was imported to display the appointment details on confirming
- Button loading state was added on submission of the form (visual indicator to the user that something is actually happening)
- reset the form state to the default values after submitting (because the form would register as invalid)

**Review by 5hraddha — APPROVED** [review]
Looks good @mentalcaries!

**Pull request merged**
