### PR TITLE
Create an Admin Dashboard where admins can view appointment requests

### LINKED ISSUE #78: Refactor / Rewrite the Admin Dashboard component along with popups to hook up Shadcn UI library
We have Admin Dashboard component. We need to hook to up the UI Library to the Dashboard and popups. Need to see if we need to refactor or completely rewrite the components.

### PR DESCRIPTION
**Pull request by 5hraddha**
## Description

In this PR, I've:

- [x] Hooked up Shadcn UI library to create a data table component that will showcase all the appointment requests in 4 groups - **Emergency**, **Normal**, **Scheduled** and **Cancelled**.
- [x] Formatted dates to show on the UI in a human readable form.
- [x] Implemented pagination.
- [x] Implemented the functionality to allow user to see arbitrary number of rows per page.
- [x] Enable sorting (both ascending and descending orders) on certain columns.
- [x] Enable the ability to toggle column visibility on all the columns except `Status`.
- [x] Created a new column - `Full Name` combining `First Name` and `Last Name`.
- [x] Derived a new column - `Status` to display badges depending on the whether the appointment request is an emergency, or is scheduled or is cancelled or is a normal request waiting for scheduling.
- [x] Enabled search and filtering capability on the data table for the patient names.
- [x] Implemented Real Time Sync with Supabase DB.

## Related Issue

Closes #78

## Acceptance Criteria

We have Admin Dashboard component. We need to hook to up the UI Library to the Dashboard and popups. Need to see if we need to refactor or completely rewrite the components.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### After

image

### CODE REVIEW

**Review by mentalcaries — COMMENTED** [review]
Looks great @5hraddha! I love the tabs and pagination.

I think the one tab that we forgot was "All Appointments" that shows all regardless of the status.

The other thing I am thinking is to hide some of the columns on the dashboard so that users don't have to scroll horizontally. I think this view should have enough information to be able to call and patient and set up the appointment.

With that, I don't think we need Email, Scheduled Date or Scheduled time. Once the "Scheduled" badge is present, staff should know that the appointment was booked.  Those other details can be accessible in the popup.

**Comment by 5hraddha** [comment]
Sounds good @mentalcaries. I will update the UI accordingly.

**Comment by 5hraddha** [comment]
> Looks great @5hraddha! I love the tabs and pagination.
> 
> I think the one tab that we forgot was "All Appointments" that shows all regardless of the status.
> 
> The other thing I am thinking is to hide some of the columns on the dashboard so that users don't have to scroll horizontally. I think this view should have enough information to be able to call and patient and set up the appointment.
> 
> With that, I don't think we need Email, Scheduled Date or Scheduled time. Once the "Scheduled" badge is present, staff should know that the appointment was booked. Those other details can be accessible in the popup.

@mentalcaries I have implemented the suggested UI changes as now. 
image

**Review by mentalcaries — APPROVED** [review]
The dashboard looks so clean now!
Fantastic!

**Pull request merged**
