### PR TITLE
Na/display admin name logo

### LINKED ISSUE #90: The dashboard should give some indication about who is logged in
As we now have multiple user support, the dashboard should display somewhere the credentials somewhere, i.e current user, maybe in the form of an avatar:
image

The Dashboard should also show some elements to make it feel customised to that specific office: Office name and logo

### PR DESCRIPTION
**Pull request by NuriyaAkh**
## Description

Added the practice logo and name, based on the users/practice email
## Related Issue

closes #90
## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before
Screenshot 2023-09-10 at 1 44 10 PM

### After
Screenshot 2023-09-10 at 1 41 09 PM

### CODE REVIEW

**Comment by mentalcaries** [comment]
@NuriyaAkh Looks good. I wonder if we could reduce the font size for the `Connectient Control Tower` and make the practice name/logo a bit bigger so it's more of the focus?

**Comment by NuriyaAkh** [comment]
@mentalcaries , what do you think?
Screenshot 2023-09-10 at 9 57 38 PM

**Comment by mentalcaries** [comment]
> @mentalcaries , what do you think? Screenshot 2023-09-10 at 9 57 38 PM

Looks great!

**Review by mentalcaries — APPROVED** [review]
Nice work!

**Pull request merged**
